package componenteJuego;

/**
 *
 * @author Fernanda
 */
public class PanelPrincipalJuego extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipalJuego
     */
    Logica logica = new Logica();
    String inputUsuario;
    public PanelPrincipalJuego() {
        initComponents();
        textFieldUsuario.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInicio = new javax.swing.JButton();
        textFieldUsuario = new javax.swing.JTextField();
        botonComparar = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        labelPuntajeParcial = new javax.swing.JLabel();
        labelPuntajeTotal = new javax.swing.JLabel();
        labelIntentos = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 400));

        botonInicio.setText("Iniciar Juego");
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        textFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsuarioActionPerformed(evt);
            }
        });

        botonComparar.setText("Comparar");
        botonComparar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCompararMouseClicked(evt);
            }
        });
        botonComparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCompararActionPerformed(evt);
            }
        });

        labelResultado.setText("Resultado: ");

        labelPuntajeParcial.setText("Puntaje Parcial: ");

        labelPuntajeTotal.setText("Puntaje Total: ");

        labelIntentos.setText("Intentos: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonInicio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonComparar))
                            .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPuntajeTotal)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPuntajeParcial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelIntentos)))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelResultado)
                .addGap(18, 18, 18)
                .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInicio)
                    .addComponent(botonComparar))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntentos)
                    .addComponent(labelPuntajeParcial, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(labelPuntajeTotal)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        logica.generarColoresRandom();
        textFieldUsuario.setEnabled(true); 
        botonComparar.setEnabled(true);
        if(logica.getIntentos() == 0  || logica.getAciertoTotal() == 4) {
            logica.resetJuego();
            labelPuntajeParcial.setText("Puntaje parcial: " + logica.getAciertoParcial());
            labelPuntajeTotal.setText("Puntaje Total: " + logica.getAciertoTotal());
            labelIntentos.setText("Intentos: " + logica.getIntentos());
        }
    }//GEN-LAST:event_botonInicioActionPerformed

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
      
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonCompararMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCompararMouseClicked
        
    }//GEN-LAST:event_botonCompararMouseClicked

    private void textFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsuarioActionPerformed
      
    }//GEN-LAST:event_textFieldUsuarioActionPerformed

    private void botonCompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCompararActionPerformed
        logica.compararArrays();
        
        inputUsuario = textFieldUsuario.getText();
        logica.setInputUsuario(inputUsuario);
        
        labelPuntajeParcial.setText("Puntaje parcial: " + logica.getAciertoParcial());
        labelPuntajeTotal.setText("Puntaje Total: " + logica.getAciertoTotal());
        labelIntentos.setText("Intentos: " + logica.getIntentos());      
        
        if(logica.getIntentos() > 0) {
            if(logica.getAciertoTotal() !=4) {
                labelResultado.setText("Ha fallado!");
                logica.resetPuntajes();
            }
            if(logica.getAciertoTotal() == 4) {        
                labelResultado.setText("Ha Ganado!!");
                botonComparar.setEnabled(false);
                logica.resetJuego();             
            }
        }
        else if(logica.getIntentos() == 0) {        
            labelResultado.setText("Game Over!!");
            botonComparar.setEnabled(false);
            textFieldUsuario.setEnabled(false); 
            logica.resetJuego();
        }
        else {

            logica.compararArrays();        
        }
    }//GEN-LAST:event_botonCompararActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComparar;
    private javax.swing.JButton botonInicio;
    private javax.swing.JLabel labelIntentos;
    private javax.swing.JLabel labelPuntajeParcial;
    private javax.swing.JLabel labelPuntajeTotal;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
